export default [
    {
        name: "Kepa Arrizabalaga",
        number: "1",
        position: "Goalkeeper",
        photo: "https://guardian.ng/wp-content/uploads/2019/02/Kepa-Arrizabalaga.jpg",
        nation: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/1280px-Flag_of_Spain.svg.png",
        ahw: "Age: 24 │ Height: 1.86m │ Weight: 85kg",
        apps: "29",
        cleansheets: "Clean Sheets: 15",
        saves: "Saves: 60",
        info: "Kepa Arrizabalaga signed for Chelsea from Athletic Bilbao on 8 August 2018 The 23-year-old Spanish international goalkeeper arrived ahead of the 2018/19 Premier League season having signed a seven-year contract at Stamford Bridge. Kepa, who has played over 100 career league games, has solid experience at the highest level having made more than 50 appearances in La Liga, his quality earning him a call-up to the Spain squad for this summer’s World Cup in Russia. Upon completing his move to Chelsea, he said: ‘It’s a very important decision for me, for my career, and also for my personal life. 'So many things attracted me to the club, all the titles the club has won, the other players, the city, the English Premier League. It’s an accumulation of things, and I am very glad Chelsea has decided to trust me and to take me in as well.’ Director Marina Granovskaia added: ‘Kepa is a talent we have admired for a long time and we are extremely excited about his arrival. He has already demonstrated fantastic quality and consistency and will be a big part of any success Chelsea have in the coming years. His long-term contract reflects the belief we have in him and we look ahead to the coming seasons with an enormous sense of optimism.’",
    },
    {
        name: "Wilfredo Caballero",
        number: "13",
        position: "Goalkeeper",
        photo: "https://guardian.ng/wp-content/uploads/2017/07/Willy-Caballero.jpg",
        nation: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/2000px-Flag_of_Argentina.svg.png",
        ahw: "Age: 37 │ Height: 1.86m │ Weight: 81kg",
        apps: "1",
        cleansheets: "Clean Sheets: 1",
        saves: "Saves: 0",
        info: "Goalkeeper Willy Caballero joined Chelsea on 1 July 2017 having been out of contract at Manchester City. He was signed to add strength to our goalkeeper resources following the departure of Asmir Begovic to Bournemouth as he has a wealth of experience at the highest level. He spent the previous three seasons at City, having started his career at Boca Juniors in his native Argentina before playing for Spanish clubs Elche and Malaga. Caballero moved to the Premier League in the summer of 2014, linking up once again with Manuel Pellegrini, whom he had played under at Malaga. The highlight of his time at City was the 2016 League Cup final when his heroics during the decisive penalty shoot-out against Liverpool ensured City secured the trophy. Caballero saved three penalties - from Lucas, Philippe Coutinho and Adam Lallana - as his team came out on top at Wembley.  In the 2016/17 season he featured in a memorable 3-1 Champions League win over Barcelona, and made a crucial penalty save from former Chelsea striker Falcao in the first leg of their last-16 knockout tie against Monaco. Caballero featured regularly towards the end of the campaign, including in City's 2-1 defeat at Stamford Bridge. On that night he saved an Eden Hazard penalty, only for the Belgian to tap home the rebound for what proved to be the winning goal.",
    }, 
    {
        name: "Rob Green",
        number: "31",
        position: "Goalkeeper",
        photo: "https://static.standard.co.uk/s3fs-public/thumbnails/image/2018/08/07/22/chelsea070818q.jpg",
        nation: "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/1280px-Flag_of_England.svg.png",
        ahw: "Age: 39 │ Height: 1.88m │ Weight: 92kg",
        apps: "0",
        cleansheets: "Clean Sheets: 0",
        saves: "Saves: 0",
        info: "Chelsea Football Club completed the signing of goalkeeper Rob Green on 26 July 2018. Green joined to provide back-up after leaving Huddersfield Town, where he spent the 2017/18 season. Upon signing a one-year contract with the Blues, the 38-year-old said: ‘It has been a whirlwind 24 hours. You are thinking about your career and where you want to go and then you get a phone call like this, and it is a short conversation. ‘It has been a pretty dramatic time for me and I can’t wait to get started. I am absolutely delighted and it is a thrill and an honour to be here.’ Green arrives with huge Premier League experience having represented Norwich City, West Ham United and Queens Park Rangers in the top flight. He has also been part of England squads at two major tournaments.",
    }, 
    {
        name: "Antonio Rudiger",
        number: "2",
        position: "Defender",
        photo: "https://www.chelseanews24.com/files/2018/09/rudiger-chelsea-2018-2019.jpg",
        nation: "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/1280px-Flag_of_Germany.svg.png",
        ahw: "Age: 26 │ Height: 1.90m │ Weight: 85kg",
        apps: "29",
        goals: "Goals: 1",
        assists: "Assists: 0",
        info: "Antonio Rudiger joined Chelsea from Italian side Roma on 9 July 2017. He signed a five-year contract. A tough tackler, Rudiger is quick on his feet and a commanding presence in the air. Despite having spent most of his career playing in central defence, he is equally comfortable at full-back. Born in Berlin, Rudiger spent time in the youth set-up at Borussia Dortmund before moving to Stuttgart. He made his Stuttgart debut in a 2012 game against Borussia Monchengladbach at the age of 18, and firmly established himself as a first-team regular during the 2013/14 campaign.In 2015 he moved to Roma, initially on loan, and after a successful maiden season in Serie A the deal was made permanent and he arrived at Stamford Bridge having acquired European experience in both the Champions League and Europa League.He featured frequently for Germany at youth international level and made his debut for the senior side in a friendly against Poland in May 2014.Having been called up to the reigning world champions’ Euro 2016 squad, Rudiger subsequently missed the tournament through injury but he was a key performer in their 2017 Confederations Cup victory in Russia. He was part of the defence which kept a clean sheet in the 1-0 win over Chile in the final.",
    },
    {
        name: "Andreas Christensen",
        number: "27",
        position: "Defender",
        photo: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/12/20/08/andreas-christensen.jpg?w968h681",
        nation: "http://flags.fmcdn.net/data/flags/w580/dk.png",
        ahw: "Age: 22 │ Height: 1.87m │ Weight: 81kg",
        apps: "3",
        goals: "Goals: 0",
        assists: "Assists: 0",
        info: "A tall, ball-playing centre-back, Andreas Christensen spent eight years at Brondby before joining Chelsea ahead of many other suitors before the 2012/13 campaign. He wasted little time in displaying his composure and assuredness at the heart of defence for our youth team, impressing enough to earn himself an Under-21 debut before Christmas; however it was in the FA Youth Cup where he most grabbed attention. He scored the first goal in the fourth round at the Valley to inspire a fightback against Charlton after the Under-18s had fallen 2-0 behind, and played in all but two of the ties en route to the final. His total of 11 Under-21 appearances for the season underlined a level of maturity in his play beyond his years, and he made his European debut in the NextGen Series for Under-19s in a defensive midfield role against Ajax in December 2012. Christensen’s impressive first campaign earned him a spot on the bench for the final game of the season against Everton and, while he didn’t enter the fray to make a senior appearance, he was involved in a post-season tour to the USA. After signing a professional contract in the summer, he spent 2013/14 working predominantly with Dermot Drummy’s Under-21 group, featuring on 25 occasions as they topped the table and then won the league play-offs. He scored his first Under-21 goal in a 2-1 win over Manchester City in October and started every FA Youth Cup tie from the fifth round onwards as Adi Viveash’s youngsters won a memorable final against Fulham.Having played throughout the senior squad's pre-season, he was named as a member of Jose Mourinho's squad for the 2014/15 campaign and made his Chelsea debut in our fourth round Capital One Cup victory at Shrewsbury (below), playing the full 90 minutes at right-back and performed a similar role in the FA Cup fourth round against Bradford. Christensen was also part of the Under-19 side which won the UEFA Youth League in April 2015 and he had his first taste of Premier League football as a late sub against Sunderland at the end of the season.",
    },
    {
        name: "Cesar Azpilicueta",
        number: "28",
        position: "Defender",
        photo: "http://www.sportreff.com/wp-content/uploads/2017/07/Azpilicueta.jpg",
        nation: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/1280px-Flag_of_Spain.svg.png",
        ahw: "Age: 29 │ Height: 1.76m │ Weight: 76kg",
        apps: "30",
        goals: "Goals: 0",
        assists: "Assists: 4",
        info: "Signed from Marseille in August 2012, weeks after representing Spain in the London Olympics, Cesar Azpilicueta soon emerged as a first-choice right-back. His ability to suppress opposition wingers immediately impressed, along with his dependability in possession and increasing willingness to join the team’s attacks. A strong beginning to life at Stamford Bridge earned Azpilicueta – affectionately known as ‘Dave’ by team-mates and supporters alike – a first call-up to the full Spanish national team in early 2013, and he ended his first campaign in Chelsea blue with 48 appearances. He has since proven capable of playing left-back and as one of a back-three defence, and ended his second season at the club by winning the Chelsea Players' Player of the Year award. He won his first Premier League title in 2015.",
    },
    {
        name: "David Luiz",
        number: "30",
        position: "Defender",
        photo: "https://cdn.vox-cdn.com/thumbor/87ZRwvtzyJPtMxSYEtRy49jSRRA=/0x0:2452x3220/1200x800/filters:focal(1097x212:1489x604)/cdn.vox-cdn.com/uploads/chorus_image/image/62381519/1060208258.jpg.0.jpg",
        nation: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png",
        ahw: "Age: 31 │ Height: 1.89m │ Weight: 86kg",
        apps: "28",
        goals: "Goals: 2",
        assists: "Assists: 2",
        info: "David Luiz returned to Stamford Bridge in August 2016 following two years at Paris Saint-Germain. Having been a key member of the Chelsea team which won the Champions League and FA Cup in 2012, as well as the Europa League a year later, David Luiz enjoyed a fruitful two-season spell in France as he helped PSG secure the domestic Treble two seasons in a row. On a personal level, he was named in the Ligue 1 Team of the Year on both occasions, before making the switch back to west London. He had initially signed for the Blues on deadline day in January 2011 from Portuguese club Benfica. A 6ft 2in centre-back who can cover at either left- or right-back, and midfield, he is renowned for his skill on the ball as much as his defensive ability. He won plenty of plaudits for his early showings, and although he conceded a late penalty on his first start against Fulham, saved by Petr Cech, he went on to win the man of the match award. Ineligible for the Champions League, he retained his place in the Premier League side until a goal conceded in the opening seconds at Old Trafford torpedoed Chelsea's title chances and Carlo Ancelotti left the Brazilian out of the remaining games. He had earlier scored against United at Stamford B.."
    }
]