export default [
    {
        teamName: 'Liverpool',
        P: 31,
        W: 23,
        D: 7,
        L: 1,
        F: 70,
        A: 18,
        GD: 52,
        Pts: 76,

    },
    {
        teamName: 'Manchester City',
        P: 30,
        W: 24,
        D: 2,
        L: 4,
        F: 79,
        A: 21,
        GD: 58,
        Pts: 74,

    },
    {
        teamName: 'Tottenham Hotspur',
        P: 30,
        W: 20,
        D: 1,
        L: 9,
        F: 57,
        A: 32,
        GD: 25,
        Pts: 61,

    },
    {
        teamName: 'Arsenal',    
        P: 30,
        W: 18,
        D: 6,
        L: 6,
        F: 63,
        A: 39,
        GD: 24,
        Pts: 60,
    },
    {
       teamName: 'Manchester United',
       P: 30,
       W: 17,
       D: 7,
       L: 6,
       F: 58,
       A: 40,
       GD: 18,
       Pts: 58,
    },
    {
        teamName: 'Chelsea',
        P: 30,
        W: 17,
        D: 6,
        L: 7,
        F: 50,
        A: 33,
        GD: 17,
        Pts: 57

    },

    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Wolverhampton Wanderers',
        P: 30,
        W: 12,
        D: 8,
        L: 10,
        F: 38,
        A: 36,
        GD: 2,
        Pts: 44,
    },
    {
        teamName: 'Watford',
        P: 30,
        W: 12,
        D: 7,
        L: 11,
        F: 43,
        A: 44,
        GD: -2,
        Pts: 43,
    },
    {
        teamName: 'West Ham United',
        P: 31,
        W: 12,
        D: 6,
        L: 13,
        F: 41,
        A: 46,
        GD: -5,
        Pts: 42,
    },
    {
        teamName: 'Leicester City',
        P: 31,
        W: 12,
        D: 5,
        L: 14,
        F: 40,
        A: 43,
        GD: -3,
        Pts: 41,
    },
    {
        teamName: 'Everton',
        P: 31,
        W: 11,
        D: 7,
        L: 13,
        F: 43,
        A: 42,
        GD: 1,
        Pts: 40,
    },
    {
        teamName: 'AFC Bournemouth',
        P: 31,
        W: 11,
        D: 5,
        L: 15,
        F: 43,
        A: 56,
        GD: -13,
        Pts: 38,
    },
    {
        teamName: 'Newcastle United',
        P: 31,
        W: 9,
        D: 8,
        L: 14,
        F: 31,
        A: 40,
        GD: -9,
        Pts: 35,
    },
    {
        teamName: 'Crystal Palace',
        P: 30,
        W: 9,
        D: 6,
        L: 15,
        F: 36,
        A: 41,
        GD: -5,
        Pts: 33,
    },
    {
        teamName: 'Brighton & Hove Albion',
        P: 29,
        W: 9,
        D: 6,
        L: 14,
        F: 32,
        A: 42,
        GD: -10,
        Pts: 33,
    },
    {
        teamName: 'Southampton',
        P: 30,
        W: 7,
        D: 9,
        L: 14,
        F: 34,
        A: 50,
        GD: -16,
        Pts: 30,
    },
    {
        teamName: 'Burnley',
        P: 31,
        W: 8,
        D: 6,
        L: 17,
        F: 35,
        A: 59,
        GD: -24,
        Pts: 30,
    },
    
    {
        teamName: 'Cardiff City',
        P: 30,
        W: 8,
        D: 4,
        L: 18,
        F: 27,
        A: 57,
        GD: -30,
        Pts: 28,
    },
    {
        teamName: 'Fulham',
        P: 31,
        W: 4,
        D: 5,
        L: 22,
        F: 29,
        A: 70,
        GD: -41,
        Pts: 17,
    },
    {
        teamName: 'Huddersfield Townley',
        P: 31,
        W: 3,
        D: 5,
        L: 23,
        F: 18,
        A: 57,
        GD: -39,
        Pts: 14,
    },
  
        
]

